$axure.loadCurrentPage({
  "url":"查看反馈.html",
  "generationDate":new Date(1447684052715.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cef0497ab2d34817bac16917d51478c8",
    "type":"Axure:Page",
    "name":"查看反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f4a6238757824851b6c20fcc125dacd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":58},
            "size":{
              "width":650,
              "height":342},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a16b27bb9b2b4f7a9e0d385980a9d50f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":58},
                "size":{
                  "width":650,
                  "height":342},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看反馈/u0.png"}},
{
          "id":"4725ac36531c4a928e58bdf425cd069b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":58},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d0bcbd37d44068a77f3fc8e65a91a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":58},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"ea3d428dd47745d4ac1989751aa315f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":66},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271bd6d745314388ad317a6230a7f630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":66},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5ae517b874d46cfa5485f12c1afa603",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":202,
              "y":130},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a178cdcf6f03482d81c63dbf4e9b35f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":202,
                  "y":130},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee4b6a2745b9465aae49bd5055793b9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":130},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b8eefcf74ec432d8d9246acdcee76b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":130},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d47aa88502114df38352994a3e4cf532",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":160},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667488cf85654104912c0c7dbc619fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":160},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"761dde0409444bdea12b65ad9d2d7f01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":160},
            "size":{
              "width":439,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac05f675a4e49e298612d6a9cebd5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":160},
                "size":{
                  "width":439,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3c41c2163724648acb3357a605e146c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":189,
              "y":329},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27031d129d1341deb4d66ce7c26e75c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":189,
                  "y":329},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "描述":"点击通过"},
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"ff23078706c84b3fa1604bb1ee736a74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":219},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd7536b2a1264bacac376321ee263fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":219},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d85b20b18c042ba8f92f127b7a25b38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":219},
            "size":{
              "width":64,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a23f49a57b42c388f1de2b3ddfaa4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":219},
                "size":{
                  "width":64,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7307452f22f64c95821f1407697ed7ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":189},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47eb938c6bf147ffb58840d7590c8919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":189},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e2f55f848154bd0990490bfa1b7ce06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":189},
            "size":{
              "width":85,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc8b952747dc44d9be1467f9015cb152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":189},
                "size":{
                  "width":85,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e3e2de68c2643b49be6c1bff9e476ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":270,
              "y":329},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e98d0ae5ff2945e080a973a6ce415872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":270,
                  "y":329},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "描述":"点击通过"},
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"5c971ecd23ef4a2e8f5615e153eeaafa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":214,
              "y":255},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3c9b7e15b6c4ac683c4ec03099a9451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":214,
                  "y":255},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aca5b571826495bb9be6742aed0d21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":270,
              "y":255},
            "size":{
              "width":193,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96015735838e4327acd30b44b0088bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":270,
                  "y":255},
                "size":{
                  "width":193,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc3d15658c54417f8c10ad9f52b3c38a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":284},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a78ccfa75404c56a94518ee78b29064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":284},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55c2f183eb564bc48e7bfb82d32cebdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":271,
              "y":280},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87e6e5aed06a45508af72468b95859f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":271,
                  "y":280},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f4a6238757824851b6c20fcc125dacd3":{
      "scriptId":"u0"},
    "a16b27bb9b2b4f7a9e0d385980a9d50f":{
      "scriptId":"u1"},
    "4725ac36531c4a928e58bdf425cd069b":{
      "scriptId":"u2"},
    "66d0bcbd37d44068a77f3fc8e65a91a3":{
      "scriptId":"u3"},
    "ea3d428dd47745d4ac1989751aa315f3":{
      "scriptId":"u4"},
    "271bd6d745314388ad317a6230a7f630":{
      "scriptId":"u5"},
    "f5ae517b874d46cfa5485f12c1afa603":{
      "scriptId":"u6"},
    "a178cdcf6f03482d81c63dbf4e9b35f2":{
      "scriptId":"u7"},
    "ee4b6a2745b9465aae49bd5055793b9e":{
      "scriptId":"u8"},
    "7b8eefcf74ec432d8d9246acdcee76b1":{
      "scriptId":"u9"},
    "d47aa88502114df38352994a3e4cf532":{
      "scriptId":"u10"},
    "667488cf85654104912c0c7dbc619fe2":{
      "scriptId":"u11"},
    "761dde0409444bdea12b65ad9d2d7f01":{
      "scriptId":"u12"},
    "3ac05f675a4e49e298612d6a9cebd5a9":{
      "scriptId":"u13"},
    "c3c41c2163724648acb3357a605e146c":{
      "scriptId":"u14"},
    "27031d129d1341deb4d66ce7c26e75c1":{
      "scriptId":"u15"},
    "ff23078706c84b3fa1604bb1ee736a74":{
      "scriptId":"u16"},
    "fd7536b2a1264bacac376321ee263fdd":{
      "scriptId":"u17"},
    "5d85b20b18c042ba8f92f127b7a25b38":{
      "scriptId":"u18"},
    "c6a23f49a57b42c388f1de2b3ddfaa4d":{
      "scriptId":"u19"},
    "7307452f22f64c95821f1407697ed7ee":{
      "scriptId":"u20"},
    "47eb938c6bf147ffb58840d7590c8919":{
      "scriptId":"u21"},
    "3e2f55f848154bd0990490bfa1b7ce06":{
      "scriptId":"u22"},
    "bc8b952747dc44d9be1467f9015cb152":{
      "scriptId":"u23"},
    "3e3e2de68c2643b49be6c1bff9e476ea":{
      "scriptId":"u24"},
    "e98d0ae5ff2945e080a973a6ce415872":{
      "scriptId":"u25"},
    "5c971ecd23ef4a2e8f5615e153eeaafa":{
      "scriptId":"u26"},
    "c3c9b7e15b6c4ac683c4ec03099a9451":{
      "scriptId":"u27"},
    "0aca5b571826495bb9be6742aed0d21a":{
      "scriptId":"u28"},
    "96015735838e4327acd30b44b0088bbe":{
      "scriptId":"u29"},
    "dc3d15658c54417f8c10ad9f52b3c38a":{
      "scriptId":"u30"},
    "6a78ccfa75404c56a94518ee78b29064":{
      "scriptId":"u31"},
    "55c2f183eb564bc48e7bfb82d32cebdc":{
      "scriptId":"u32"},
    "87e6e5aed06a45508af72468b95859f3":{
      "scriptId":"u33"}}});