$axure.loadCurrentPage({
  "url":"新增页面.html",
  "generationDate":new Date(1447684051845.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"84595e80f9e34b6fa340c281ab97c53c",
    "type":"Axure:Page",
    "name":"新增页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7e41b4532484d0198ce42844054b34c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":412},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c08c599c813b41348bc61138fbe2adc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":412},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增页面/u0.png"}},
{
          "id":"96de8a9f8c6745efa1728e114ae4a22c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3fedc6542334ec3930ed880e951495c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"ab14358a62ca45c5bab971c41cf8381d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecda2668708841a6b7abbfa3d000948e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39cad3f6ee6548a38ab54ffc103249ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":77},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5f33e44a2a42a4a566910bba5d7e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":77},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"aff51b8228e24affbd14a17cbaa7f829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":202,
              "y":133},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7967d73f92546ee9223f3b342c7da68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":202,
                  "y":133},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47ee7252b87440c090373358988dc717",
          "label":"产品标题",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":279,
              "y":128},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入页面对应url"},
{
          "id":"1714d8e3ce79493cbd10c87f529db9c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":216,
              "y":175},
            "size":{
              "width":45,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595b361fb72c43118c4cea1a6d36ef72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":216,
                  "y":175},
                "size":{
                  "width":45,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"843e7ac72eaf4d1e8d23a604271ed1b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":213,
              "y":248},
            "size":{
              "width":48,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"215e317062614ed3ab69c297d5f4b2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":213,
                  "y":248},
                "size":{
                  "width":48,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9d0ba1d02e24398b104a3d3151968c5",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":248},
            "size":{
              "width":403,
              "height":145}},
          "adaptiveStyles":{
}},
{
          "id":"d2cd4896fba44825a3218bfa6a2b1379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":204,
              "y":210},
            "size":{
              "width":57,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e03c2da0b2449049d354b738b6b6a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":204,
                  "y":210},
                "size":{
                  "width":57,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79ca3dba2e9d4c86a9f23a6e776af4db",
          "label":"产品标题",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":279,
              "y":205},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入关键词，以；隔开"},
{
          "id":"988943c6d2a040bc95142b4a7f0bf27c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":372,
              "y":420},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a867a2b78fe49c6afbf37fa0e2100b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":372,
                  "y":420},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"9f82d75a94654369bfda51c5da175c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "location":{
              "x":444,
              "y":428},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"848a60d176f24abb8f9f1d9c931e169e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "location":{
                  "x":444,
                  "y":428},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b743c0e565da4a7b8ffd1338496475fd",
          "label":"产品标题",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":279,
              "y":170},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入标题"}]}},
  "masters":{
},
  "objectPaths":{
    "a7e41b4532484d0198ce42844054b34c":{
      "scriptId":"u0"},
    "c08c599c813b41348bc61138fbe2adc9":{
      "scriptId":"u1"},
    "96de8a9f8c6745efa1728e114ae4a22c":{
      "scriptId":"u2"},
    "e3fedc6542334ec3930ed880e951495c":{
      "scriptId":"u3"},
    "ab14358a62ca45c5bab971c41cf8381d":{
      "scriptId":"u4"},
    "ecda2668708841a6b7abbfa3d000948e":{
      "scriptId":"u5"},
    "39cad3f6ee6548a38ab54ffc103249ac":{
      "scriptId":"u6"},
    "7d5f33e44a2a42a4a566910bba5d7e2a":{
      "scriptId":"u7"},
    "aff51b8228e24affbd14a17cbaa7f829":{
      "scriptId":"u8"},
    "c7967d73f92546ee9223f3b342c7da68":{
      "scriptId":"u9"},
    "47ee7252b87440c090373358988dc717":{
      "scriptId":"u10"},
    "1714d8e3ce79493cbd10c87f529db9c6":{
      "scriptId":"u11"},
    "595b361fb72c43118c4cea1a6d36ef72":{
      "scriptId":"u12"},
    "843e7ac72eaf4d1e8d23a604271ed1b8":{
      "scriptId":"u13"},
    "215e317062614ed3ab69c297d5f4b2b7":{
      "scriptId":"u14"},
    "a9d0ba1d02e24398b104a3d3151968c5":{
      "scriptId":"u15"},
    "d2cd4896fba44825a3218bfa6a2b1379":{
      "scriptId":"u16"},
    "9e03c2da0b2449049d354b738b6b6a81":{
      "scriptId":"u17"},
    "79ca3dba2e9d4c86a9f23a6e776af4db":{
      "scriptId":"u18"},
    "988943c6d2a040bc95142b4a7f0bf27c":{
      "scriptId":"u19"},
    "9a867a2b78fe49c6afbf37fa0e2100b8":{
      "scriptId":"u20"},
    "9f82d75a94654369bfda51c5da175c8e":{
      "scriptId":"u21"},
    "848a60d176f24abb8f9f1d9c931e169e":{
      "scriptId":"u22"},
    "b743c0e565da4a7b8ffd1338496475fd":{
      "scriptId":"u23"}}});