$axure.loadCurrentPage({
  "url":"查看机构.html",
  "generationDate":new Date(1447684045393.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f014bc1949c94ea5a12862a9231600be",
    "type":"Axure:Page",
    "name":"查看机构",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a4ad9d56da2d47a0a7152aa7653bffc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":772},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34d05019f48a4be9b26921967387aed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":772},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看机构/u0.png"}},
{
          "id":"6dc64dacc6434362b051e5535344f387",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df301220cb644ad8bcb53e44ddebc6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"5906346621594252b63744d8d7636d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668bb2ed574b479bb8cd412e65373207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf1c850c0fb44f728de20a3f73ebe7ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":77},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee66d1d84c3349988cf6d51caca33173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":77},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"61ff12ab08614aedaca33d522c5277f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":735},
            "size":{
              "width":67,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f8eb00f46ac4473bb4d66c132a19992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":735},
                "size":{
                  "width":67,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4432dde62e5e441d84dce81d42a0f562",
          "label":"激活状态",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":734},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5e3cbe5b770c4467ace8ba0f71fa5561",
              "label":"未激活",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5552ee0b62a342b1b39dcf8e877e292f",
                  "label":"绑定用户",
                  "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":67,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa65eaabb5cb4b6ab6cee0909deb49a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":67,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 激活状态 到 已激活",
                              "panelsToStates":[{
                                  "panelPath":["4432dde62e5e441d84dce81d42a0f562"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "annotation":{
                    "描述":"未激活状态下，显示绑定用户按钮，点击绑定用户按钮进入绑定用户列表页，可选中一个用户进行账号绑定，绑定成功后，该用户变为已激活状态"},
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f47abc23ed3f4aadad3839ab88bfafa8",
                  "label":"",
                  "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a869bf7198bb4fcca926028b274aebbd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"7411665339c346148eda86e89a64e6aa",
              "label":"已激活",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7507d8f7658c433589929e3178ea9d90",
                  "label":"绑定用户",
                  "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":67,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e8378f4764c438bbbcd6d7fd138ab98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":67,
                          "y":0},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "描述":"已激活状态下，以超链接形式显示该机构对应的管理员用户名，点击进入该管理员用户对应账号详情"},
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f1c72aaec87448aaa57a88ec66a9efa8",
                  "label":"",
                  "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00ed3dd735434f438c9c76502a8af74a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"231d0c37cdca44a3a3c6bc27e5ca41c3",
                  "label":"绑定用户",
                  "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":170,
                      "y":0},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f06fb20950014cb19cd3a88c02809232",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4432dde62e5e441d84dce81d42a0f562",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":170,
                          "y":0},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "描述":"已激活状态下，可点击修改重新选择对应管理用户"},
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"49ca6e48e8f34db799fe8075d3fd5032",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":200,
              "y":780},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374a4b22ed9f49d896e39736e0cd93e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":200,
                  "y":780},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"6ca0c95f99514b46b53eba34882afdb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":140},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca5dd46fc614b98879a46f1a774fd54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":140},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f906b888f52d43c588fc3142f2e4fbc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":140},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e629a9cf27c4415e82fba18e24e242fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":140},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3cc44201c5048e8aeacd205d236903e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":180},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6d64fb05744770a375038d090f01ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":180},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fe91c6ea27543a4b4f828a8ca504605",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":180},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8355cf435b914076a2019944ffb682f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":180},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81618d27644a483c9071bd725ee0363e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":211},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23f570d4fdf44f5a0e3e3bf8e578320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":211},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aab5790e121749499bcc1edc78385983",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":211},
            "size":{
              "width":133,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf9aa3d0e4a944f297f82305561a5f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":211},
                "size":{
                  "width":133,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56b43404865e48aba06dfea94461530d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":246},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b5e50e5d7cc49ffaee1b45c34a32eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":246},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb8fdcbfbfdb4027a5f255e91eba97fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":246},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa691812921464a896ede1592ff1350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":246},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04fdf2e8b7304e7e97c3e95ca0cdccd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":282},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51eb46afca854774847944f6e914688f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":282},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38fe97e026ee42168cac3122075fbeba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":282},
            "size":{
              "width":104,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc38709520444e39806591b88c5a05d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":282},
                "size":{
                  "width":104,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"825755de30da4212bf0edf0e7d3c2680",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":320},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f591dfe6bde94336a5f154fa3c806281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":320},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccdcb4b2443446f1b852f879fa1a95b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":320},
            "size":{
              "width":79,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430b465d7cfd4ede95a3196bc0490199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":320},
                "size":{
                  "width":79,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"576801322b70435986fe9fe0b1bef10d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":362},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77746955f7594d1eb38c3a49ec29797d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":362},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e5e0136c2384120b00c7e802ed89db0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":271,
              "y":366},
            "size":{
              "width":429,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8990a519c54720b1c1e00a8cf0bcd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":271,
                  "y":366},
                "size":{
                  "width":429,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f54a64ec5bba434d845673789ac980f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":580,
              "y":129},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61dc932cf0884ca69e5d2d8b0fad6817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":580,
                  "y":129},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"577608e7cf4b4a5799a6be405813ce0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":652,
              "y":129},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b58e08892d0341d2b6ab94569e42b90f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":652,
                  "y":129},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"681cfe58b7c74f6d9e342d887a316ca2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":508,
              "y":129},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a0c7b0fc8b04ac2a2a74c0f727f2b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":508,
                  "y":129},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"eaf9a6bfabee40748e54187fef1336a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":224,
              "y":605},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db3cde30d2b046198afe398fc7472498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":224,
                  "y":605},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b746f727fcb94936a8110681aeefee21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":605},
            "size":{
              "width":124,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"065064f78b3c4e919b73eaf64256cb07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":605},
                "size":{
                  "width":124,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57236861fd1f493ba9a9d38fc75c96c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":212,
              "y":637},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0a3a7590944e31a4765b00aa6c925c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":212,
                  "y":637},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1638c0ae929f4c3ea218d5e78dabc49e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":637},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cdb14e75aba45189eedfa716bcb2de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":637},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a78b25e81bef42359a543c23589acd65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":212,
              "y":669},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef2729a60724482b7d40de53a78ff95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":212,
                  "y":669},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef2ec3c38aaf40749366cd530c07cb1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":669},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16bb1c2235b43d5b124f1bc95a5b1d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":669},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"481192bb96c04b4696faaec15e96770a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":212,
              "y":702},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae3caf73ea564695ab9e862d94b80920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":212,
                  "y":702},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f69b4d8a0a8460898e38cf4ef29c680",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":702},
            "size":{
              "width":18,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76497a6e2e0143bc8090b62255ecaaff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":702},
                "size":{
                  "width":18,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a4ad9d56da2d47a0a7152aa7653bffc3":{
      "scriptId":"u0"},
    "34d05019f48a4be9b26921967387aed0":{
      "scriptId":"u1"},
    "6dc64dacc6434362b051e5535344f387":{
      "scriptId":"u2"},
    "df301220cb644ad8bcb53e44ddebc6f5":{
      "scriptId":"u3"},
    "5906346621594252b63744d8d7636d18":{
      "scriptId":"u4"},
    "668bb2ed574b479bb8cd412e65373207":{
      "scriptId":"u5"},
    "cf1c850c0fb44f728de20a3f73ebe7ed":{
      "scriptId":"u6"},
    "ee66d1d84c3349988cf6d51caca33173":{
      "scriptId":"u7"},
    "61ff12ab08614aedaca33d522c5277f7":{
      "scriptId":"u8"},
    "9f8eb00f46ac4473bb4d66c132a19992":{
      "scriptId":"u9"},
    "4432dde62e5e441d84dce81d42a0f562":{
      "scriptId":"u10"},
    "5552ee0b62a342b1b39dcf8e877e292f":{
      "scriptId":"u11"},
    "fa65eaabb5cb4b6ab6cee0909deb49a2":{
      "scriptId":"u12"},
    "f47abc23ed3f4aadad3839ab88bfafa8":{
      "scriptId":"u13"},
    "a869bf7198bb4fcca926028b274aebbd":{
      "scriptId":"u14"},
    "7507d8f7658c433589929e3178ea9d90":{
      "scriptId":"u15"},
    "4e8378f4764c438bbbcd6d7fd138ab98":{
      "scriptId":"u16"},
    "f1c72aaec87448aaa57a88ec66a9efa8":{
      "scriptId":"u17"},
    "00ed3dd735434f438c9c76502a8af74a":{
      "scriptId":"u18"},
    "231d0c37cdca44a3a3c6bc27e5ca41c3":{
      "scriptId":"u19"},
    "f06fb20950014cb19cd3a88c02809232":{
      "scriptId":"u20"},
    "49ca6e48e8f34db799fe8075d3fd5032":{
      "scriptId":"u21"},
    "374a4b22ed9f49d896e39736e0cd93e9":{
      "scriptId":"u22"},
    "6ca0c95f99514b46b53eba34882afdb9":{
      "scriptId":"u23"},
    "dca5dd46fc614b98879a46f1a774fd54":{
      "scriptId":"u24"},
    "f906b888f52d43c588fc3142f2e4fbc2":{
      "scriptId":"u25"},
    "e629a9cf27c4415e82fba18e24e242fd":{
      "scriptId":"u26"},
    "b3cc44201c5048e8aeacd205d236903e":{
      "scriptId":"u27"},
    "5f6d64fb05744770a375038d090f01ba":{
      "scriptId":"u28"},
    "8fe91c6ea27543a4b4f828a8ca504605":{
      "scriptId":"u29"},
    "8355cf435b914076a2019944ffb682f5":{
      "scriptId":"u30"},
    "81618d27644a483c9071bd725ee0363e":{
      "scriptId":"u31"},
    "d23f570d4fdf44f5a0e3e3bf8e578320":{
      "scriptId":"u32"},
    "aab5790e121749499bcc1edc78385983":{
      "scriptId":"u33"},
    "bf9aa3d0e4a944f297f82305561a5f19":{
      "scriptId":"u34"},
    "56b43404865e48aba06dfea94461530d":{
      "scriptId":"u35"},
    "8b5e50e5d7cc49ffaee1b45c34a32eda":{
      "scriptId":"u36"},
    "fb8fdcbfbfdb4027a5f255e91eba97fe":{
      "scriptId":"u37"},
    "5fa691812921464a896ede1592ff1350":{
      "scriptId":"u38"},
    "04fdf2e8b7304e7e97c3e95ca0cdccd4":{
      "scriptId":"u39"},
    "51eb46afca854774847944f6e914688f":{
      "scriptId":"u40"},
    "38fe97e026ee42168cac3122075fbeba":{
      "scriptId":"u41"},
    "5fc38709520444e39806591b88c5a05d":{
      "scriptId":"u42"},
    "825755de30da4212bf0edf0e7d3c2680":{
      "scriptId":"u43"},
    "f591dfe6bde94336a5f154fa3c806281":{
      "scriptId":"u44"},
    "ccdcb4b2443446f1b852f879fa1a95b0":{
      "scriptId":"u45"},
    "430b465d7cfd4ede95a3196bc0490199":{
      "scriptId":"u46"},
    "576801322b70435986fe9fe0b1bef10d":{
      "scriptId":"u47"},
    "77746955f7594d1eb38c3a49ec29797d":{
      "scriptId":"u48"},
    "2e5e0136c2384120b00c7e802ed89db0":{
      "scriptId":"u49"},
    "da8990a519c54720b1c1e00a8cf0bcd2":{
      "scriptId":"u50"},
    "f54a64ec5bba434d845673789ac980f2":{
      "scriptId":"u51"},
    "61dc932cf0884ca69e5d2d8b0fad6817":{
      "scriptId":"u52"},
    "577608e7cf4b4a5799a6be405813ce0e":{
      "scriptId":"u53"},
    "b58e08892d0341d2b6ab94569e42b90f":{
      "scriptId":"u54"},
    "681cfe58b7c74f6d9e342d887a316ca2":{
      "scriptId":"u55"},
    "8a0c7b0fc8b04ac2a2a74c0f727f2b35":{
      "scriptId":"u56"},
    "eaf9a6bfabee40748e54187fef1336a1":{
      "scriptId":"u57"},
    "db3cde30d2b046198afe398fc7472498":{
      "scriptId":"u58"},
    "b746f727fcb94936a8110681aeefee21":{
      "scriptId":"u59"},
    "065064f78b3c4e919b73eaf64256cb07":{
      "scriptId":"u60"},
    "57236861fd1f493ba9a9d38fc75c96c8":{
      "scriptId":"u61"},
    "ca0a3a7590944e31a4765b00aa6c925c":{
      "scriptId":"u62"},
    "1638c0ae929f4c3ea218d5e78dabc49e":{
      "scriptId":"u63"},
    "0cdb14e75aba45189eedfa716bcb2de2":{
      "scriptId":"u64"},
    "a78b25e81bef42359a543c23589acd65":{
      "scriptId":"u65"},
    "3ef2729a60724482b7d40de53a78ff95":{
      "scriptId":"u66"},
    "ef2ec3c38aaf40749366cd530c07cb1e":{
      "scriptId":"u67"},
    "b16bb1c2235b43d5b124f1bc95a5b1d2":{
      "scriptId":"u68"},
    "481192bb96c04b4696faaec15e96770a":{
      "scriptId":"u69"},
    "ae3caf73ea564695ab9e862d94b80920":{
      "scriptId":"u70"},
    "1f69b4d8a0a8460898e38cf4ef29c680":{
      "scriptId":"u71"},
    "76497a6e2e0143bc8090b62255ecaaff":{
      "scriptId":"u72"}}});