$axure.loadCurrentPage({
  "url":"举报流程.html",
  "generationDate":new Date(1447684053391.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"12f6c467f55a4bc5a5a4033964280f58",
    "type":"Axure:Page",
    "name":"举报流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1cea1c006fd44072b7d91f5ed2eaff84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":221,
              "y":209},
            "size":{
              "width":220,
              "height":751}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0756599917154bbfb715db2099917c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":221,
                  "y":209},
                "size":{
                  "width":220,
                  "height":751}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u0.png"}},
{
          "id":"8b6e9e6768494606b052beda94567d81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":659,
              "y":209},
            "size":{
              "width":251,
              "height":751}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5dcbbb0d2f49f4be9938b385a8d2a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":659,
                  "y":209},
                "size":{
                  "width":251,
                  "height":751}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u2.png"}},
{
          "id":"34c711913ae64794bb0eda421e52a406",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":290},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6391d6d240bc47f79ca9b6f76dc5017c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":290},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u0.png"}},
{
          "id":"d7b9b105506e4e2aa2e21dd3080d7b40",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f4c54a88fc4b7b84a0b2ea4fa049ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u2.png"}},
{
          "id":"71683cfbb81548b084558b1b727320cb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed1f52ae12b4fe18f6c9a2d52189acc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":350}},
              "adaptiveStyles":{
}}]},
{
          "id":"37cd4c3743654bd190e34c81ac7b7f7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":497,
              "y":53},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e8d43457bc45dcbb4226404fd302ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":497,
                  "y":53},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac36a7b88748469f837ee7a9b65767a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":221,
              "y":150},
            "size":{
              "width":220,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b56aa54891a451896381cc07d85c280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":221,
                  "y":150},
                "size":{
                  "width":220,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u12.png"}},
{
          "id":"40fda37feecf42248a9d2891ec7ab77a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":659,
              "y":150},
            "size":{
              "width":251,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"546c82701b5b48eea334ec2c5e4ef683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":659,
                  "y":150},
                "size":{
                  "width":251,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u14.png"}},
{
          "id":"010d00fc94074c71b108691163f322ec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":734.5,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f6c41bd1da44b3b28d84ccf4be0aa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734.5,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u2.png"}},
{
          "id":"452287be006a4455a8cad26500b407ed",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":734.5,
              "y":540},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b6068bacfd432d8148e39548de1030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734.5,
                  "y":540},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u4.png"}},
{
          "id":"b783f124e5ba4666af8b26786486a127",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":784,
              "y":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58c9d8a30ad4a9fb32114f58cf5351c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":784,
                  "y":460}},
              "adaptiveStyles":{
}}]},
{
          "id":"be049c0774a24dd4a2b7183ddbe33e0f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e577b5d45f5480db37b0b6fd0264940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":430}},
              "adaptiveStyles":{
}}]},
{
          "id":"169e635531dc482190e6d11f87959777",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":784,
              "y":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acdbeded5dfd436dbaf393ad226818f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":784,
                  "y":600}},
              "adaptiveStyles":{
}}]},
{
          "id":"48a3badd0f9a45cabc7b100e1db20040",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":209},
            "size":{
              "width":220,
              "height":751}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c989215b0bee4f74848df4942e5f5725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":209},
                "size":{
                  "width":220,
                  "height":751}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u0.png"}},
{
          "id":"93def5ff56f44468bdb9ae6eb0fa04a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":440,
              "y":150},
            "size":{
              "width":220,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558cca0d29964b2886ca8ed19b557445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":440,
                  "y":150},
                "size":{
                  "width":220,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报流程/u12.png"}},
{
          "id":"3aff8603c9b4401a86383a76c9bc5be1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":540},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d2c27eb22ed454da7d8a90e0c8fec1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":540},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u2.png"}},
{
          "id":"e1032293d3484292b6db3516a5f90176",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":680},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539c37b93d774c5b854b8de35b9c5dd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":680},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u2.png"}},
{
          "id":"3def02584a894d35955c459d4f065c71",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":810},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f3647d50aa4de6b5c8d32ecffe643a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":810},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价流程/u0.png"}},
{
          "id":"62c0bccd57654ea5a9afdafd75f9eb2d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":734,
              "y":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb613d48b18432894eb4cfc39e95536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734,
                  "y":570}},
              "adaptiveStyles":{
}}]},
{
          "id":"f804d57dd8864b44bee6c6e7f96596d1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":680}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c346c18aaa74f4bbe3de329ee004519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":680}},
              "adaptiveStyles":{
}}]},
{
          "id":"078a7d2a7235465b95fd3f5da2d867c7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d17576a1fe944f989b85968703ba945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":570}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "1cea1c006fd44072b7d91f5ed2eaff84":{
      "scriptId":"u0"},
    "0756599917154bbfb715db2099917c89":{
      "scriptId":"u1"},
    "8b6e9e6768494606b052beda94567d81":{
      "scriptId":"u2"},
    "bf5dcbbb0d2f49f4be9938b385a8d2a9":{
      "scriptId":"u3"},
    "34c711913ae64794bb0eda421e52a406":{
      "scriptId":"u4"},
    "6391d6d240bc47f79ca9b6f76dc5017c":{
      "scriptId":"u5"},
    "d7b9b105506e4e2aa2e21dd3080d7b40":{
      "scriptId":"u6"},
    "21f4c54a88fc4b7b84a0b2ea4fa049ea":{
      "scriptId":"u7"},
    "71683cfbb81548b084558b1b727320cb":{
      "scriptId":"u8"},
    "7ed1f52ae12b4fe18f6c9a2d52189acc":{
      "scriptId":"u9"},
    "37cd4c3743654bd190e34c81ac7b7f7a":{
      "scriptId":"u10"},
    "27e8d43457bc45dcbb4226404fd302ce":{
      "scriptId":"u11"},
    "ac36a7b88748469f837ee7a9b65767a2":{
      "scriptId":"u12"},
    "1b56aa54891a451896381cc07d85c280":{
      "scriptId":"u13"},
    "40fda37feecf42248a9d2891ec7ab77a":{
      "scriptId":"u14"},
    "546c82701b5b48eea334ec2c5e4ef683":{
      "scriptId":"u15"},
    "010d00fc94074c71b108691163f322ec":{
      "scriptId":"u16"},
    "d5f6c41bd1da44b3b28d84ccf4be0aa2":{
      "scriptId":"u17"},
    "452287be006a4455a8cad26500b407ed":{
      "scriptId":"u18"},
    "00b6068bacfd432d8148e39548de1030":{
      "scriptId":"u19"},
    "b783f124e5ba4666af8b26786486a127":{
      "scriptId":"u20"},
    "d58c9d8a30ad4a9fb32114f58cf5351c":{
      "scriptId":"u21"},
    "be049c0774a24dd4a2b7183ddbe33e0f":{
      "scriptId":"u22"},
    "2e577b5d45f5480db37b0b6fd0264940":{
      "scriptId":"u23"},
    "169e635531dc482190e6d11f87959777":{
      "scriptId":"u24"},
    "acdbeded5dfd436dbaf393ad226818f5":{
      "scriptId":"u25"},
    "48a3badd0f9a45cabc7b100e1db20040":{
      "scriptId":"u26"},
    "c989215b0bee4f74848df4942e5f5725":{
      "scriptId":"u27"},
    "93def5ff56f44468bdb9ae6eb0fa04a8":{
      "scriptId":"u28"},
    "558cca0d29964b2886ca8ed19b557445":{
      "scriptId":"u29"},
    "3aff8603c9b4401a86383a76c9bc5be1":{
      "scriptId":"u30"},
    "4d2c27eb22ed454da7d8a90e0c8fec1b":{
      "scriptId":"u31"},
    "e1032293d3484292b6db3516a5f90176":{
      "scriptId":"u32"},
    "539c37b93d774c5b854b8de35b9c5dd4":{
      "scriptId":"u33"},
    "3def02584a894d35955c459d4f065c71":{
      "scriptId":"u34"},
    "b8f3647d50aa4de6b5c8d32ecffe643a":{
      "scriptId":"u35"},
    "62c0bccd57654ea5a9afdafd75f9eb2d":{
      "scriptId":"u36"},
    "abb613d48b18432894eb4cfc39e95536":{
      "scriptId":"u37"},
    "f804d57dd8864b44bee6c6e7f96596d1":{
      "scriptId":"u38"},
    "3c346c18aaa74f4bbe3de329ee004519":{
      "scriptId":"u39"},
    "078a7d2a7235465b95fd3f5da2d867c7":{
      "scriptId":"u40"},
    "7d17576a1fe944f989b85968703ba945":{
      "scriptId":"u41"}}});