$axure.loadCurrentPage({
  "url":"查看审核.html",
  "generationDate":new Date(1447684047711.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ca2a7ac8916f4b43af00730a0996266a",
    "type":"Axure:Page",
    "name":"查看审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e54b70f8ac0444d9b92ad8a6831b94b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":502},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978cf48610584b1e8fb502342b9deb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":502},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看审核/u0.png"}},
{
          "id":"0418a572a70641d1b10d9e5c9fbe3a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b5c806195f410ebb67b312dc9d5570",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"07c0091e4ccb484c9822c008d9ee57cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a479f2fd95cb4c998777ebb768529cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"164cef784acc4fdbbc1eba6a71bce106",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":77},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea6d0f2057b24302b69b7464a53916b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":77},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"7c80ae15702742c2b7be2bec97c2bd0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":170},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4e525e098334d29b6077c6a5d78e4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":170},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73ea2c78f9c24fb18e680b123e8bd4f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":170},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8797708929a547bc9c5e5fa3ee419061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":170},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"可点击进入该机构详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34f081cd2eee4c388f7f26754b09bd97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":223},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc31ee88883347d081a1dc2827252b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":223},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7474c135860a4cde8e2589d0dbcd4dc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":223},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8243501d209e44838c78a59d70d810ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":223},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"发起审核的用户名，可点击进入该用户详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7329b65009504c3b86d018e2491e1946",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":449},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84faee81e6d04764a8992dd8a9aeece4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":449},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0994a3dfd9045a3ae36db88315effee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":330,
              "y":499},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ba7e96a159489d9db24322cfaf55f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":330,
                  "y":499},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"1bf4812d62b2459b96a1bf549719c74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":402,
              "y":499},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58823c4cd1a648119c86b7a3517d2703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":402,
                  "y":499},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"beec299f260d411db542c1dad98eb379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":449},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e0c8b50f844816892a8985998ad8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":449},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67ea05fe666a4a02bd02d05901b3b1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":484,
              "y":507},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b33cbe8fdd945ec9aeb6657e0fa1705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":484,
                  "y":507},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52705254cfa441e293d68f71d22794aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":730},
            "size":{
              "width":650,
              "height":650},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35593a4a1a5d4d869d220b7ddf6ebead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":730},
                "size":{
                  "width":650,
                  "height":650},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看审核/u26.png"}},
{
          "id":"797baf236d5c44fea1b6b9f318ccc2d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":730},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd2dde083a041059cf9a90db90a7da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":730},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"af51e7313ba04849930913da1f801413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":738},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20baac38e6a549eca5b1a6f05b3d588b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":738},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b165fca23cdd46579a2d11d310dd77e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":739},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9075605d39114ac79bba346a283ce309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":739},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"da47d477e43544199d33e304b34e078a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":840},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e1d359d0023470f8c0d2ff6e8c9a204",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":840},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7941537f56634803a4551ed9a57006ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":840},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c59b44a4ba5e4f0c98695b5c2eb9b6a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":840},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"可点击进入该机构详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"884ff0099c414207b48eafd2236a23d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":875},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da2e97b87bcd4290aa328c993af6d74a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":875},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61828db2b6d04244a27029a7a6682193",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":184,
              "y":1113},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e67ef0a306441c2b057b8481c4f1dd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":184,
                  "y":1113},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60ad1ead65ba4edb8e908748e123c3cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":265,
              "y":1113},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"226f7dcdd6bd49058a84e1bd54923499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":265,
                  "y":1113},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"发起审核的用户名，可点击进入该用户详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7265254eb45a4c3981e6633cc69c61d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":184,
              "y":1265},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457c04c48f14438b94bbb0d067392103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":184,
                  "y":1265},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ec49573e43741f19002c4d99e36f41e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":330,
              "y":1310},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241b920c330443d689ad7e313fe66b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":330,
                  "y":1310},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"d8530796a494488aa4fe6383f8eead18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":402,
              "y":1310},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54dc2b7d3a124b1c95f5415d5f97174f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":402,
                  "y":1310},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"0b5f5c8bc180495da29c626fb40c733e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":265,
              "y":1265},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbce6d3053f444deab95e1736dfe20cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":265,
                  "y":1265},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca80a6a05e5f42edb1715fcc0c6f75dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":484,
              "y":1318},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c14300a9e846b4a6bc6ad2b3c32121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":484,
                  "y":1318},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1ca9a2f319e403fa26e64bd610e86ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":135},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e424c042fb7a42c28fd39a0ce5e63293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":135},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6afb87ceebc94d70957465c2629e7793",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":135},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a4a4b37db4a423d9f0a6cdc9b626ce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":135},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"587204185c86400ebb731d2f3780861e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":267},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1eac3a086843babcfcd2a3c4fa3e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":267},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86b42cd9aecc43a391481f4a195a2eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":276,
              "y":267},
            "size":{
              "width":8,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b18deed67284f5da308607567b7b8b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":276,
                  "y":267},
                "size":{
                  "width":8,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44b6d90958a047a1b9eaa5f32499c8b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":298},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde4c6beaf47483a9a764a8d5ddadc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":298},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0325f91a1c174e80bc6d8aa3f745eabd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":369},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d9dfb4d8d6f4f65a53e1be44bf205ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":369},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7df885a38a5e4acab960fd1507acfa75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":276,
              "y":369},
            "size":{
              "width":454,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1a22ec3f5084e7c81ae4fec73d58f67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":276,
                  "y":369},
                "size":{
                  "width":454,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8448326ce64e4659b2f4313d86fc5303",
          "label":"Label.Basic",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "paddingBottom":"1",
            "location":{
              "x":397,
              "y":295},
            "size":{
              "width":60,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46de0d459421411d8e21f1a40e7ac4d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "paddingBottom":"1",
                "location":{
                  "x":397,
                  "y":295},
                "size":{
                  "width":60,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/label_basic_u82.png"}},
{
          "id":"c6c99283b2c74c41b70dc296c39846ce",
          "label":"Label.Basic",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "paddingBottom":"1",
            "location":{
              "x":459,
              "y":295},
            "size":{
              "width":60,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4454a9c87c594894988156a16b3fbc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "paddingBottom":"1",
                "location":{
                  "x":459,
                  "y":295},
                "size":{
                  "width":60,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/label_basic_u82.png"}},
{
          "id":"d080e472e0864ecf93cf545027767e0d",
          "label":"Label.Basic",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "paddingBottom":"1",
            "location":{
              "x":521,
              "y":295},
            "size":{
              "width":60,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be469f0d35546bcb2d540be2aa4485b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "paddingBottom":"1",
                "location":{
                  "x":521,
                  "y":295},
                "size":{
                  "width":60,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/label_basic_u82.png"}},
{
          "id":"d8946fff331546b4b6ca783605d5606d",
          "label":"Label.Basic",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "paddingBottom":"1",
            "location":{
              "x":273,
              "y":295},
            "size":{
              "width":60,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df83295f4f6c4407aa9482e959df4329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "paddingBottom":"1",
                "location":{
                  "x":273,
                  "y":295},
                "size":{
                  "width":60,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/label_basic_u82.png"}},
{
          "id":"91daef16bc2145c08cbc0c092aeb83c0",
          "label":"Label.Basic",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "paddingBottom":"1",
            "location":{
              "x":335,
              "y":295},
            "size":{
              "width":60,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3071c57621d94dc7bbcb2d63dbcb1654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "paddingBottom":"1",
                "location":{
                  "x":335,
                  "y":295},
                "size":{
                  "width":60,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/label_basic_u82.png"}},
{
          "id":"6c1b8a4c18e0436eb4a8a819986e0669",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":332},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbb4e7bc8e14fadba5e247fd0030cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":332},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631bd708eb4a4e22be5a8809c302c5f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":276,
              "y":329},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89446c0166d142919dbd765f18b869df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":276,
                  "y":329},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20d2f977ea6d495abb176935636fb65a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":795},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c21a335faf419bb393d4d4ca515e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":795},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1d81105c2d64ddcba24170aa1dae468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":795},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da6345fe0714cbd80776c688f97fb52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":795},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a3651b568cc4d8fb24245e4e8af78bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":875},
            "size":{
              "width":186,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ec8d53320148a68177db951353c182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":875},
                "size":{
                  "width":186,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看审核/u86.png"}},
{
          "id":"316a3477fa2d43588cdcb108732a2022",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":208,
              "y":1151},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0cd1c7a3d64df59eb67211d5c4c608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":208,
                  "y":1151},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aab61226eab14b9aa472573b0386bccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":208,
              "y":1190},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f547738bbd409db1a1c18159cbba5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":208,
                  "y":1190},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aba0633817534c919102371c253a3060",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":265,
              "y":1190},
            "size":{
              "width":145,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcda05bb9fa74d79969a5489f10d55a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":1190},
                "size":{
                  "width":145,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82781906588d498193082d18d664875a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":265,
              "y":1151},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f48814dc3b9b46d9b6dcb3c2c9259a1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":1151},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"464ae458ccc142678d8bd531a4f1fcb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":181,
              "y":1234},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"660d6cde7bf24edf98acae3325cc7b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":181,
                  "y":1234},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f61739b059b47e59a30610aad16d193",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":267,
              "y":1230},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e815bac68d6d4fdea5fe1b2697872c3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":267,
                  "y":1230},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1e54b70f8ac0444d9b92ad8a6831b94b":{
      "scriptId":"u0"},
    "978cf48610584b1e8fb502342b9deb96":{
      "scriptId":"u1"},
    "0418a572a70641d1b10d9e5c9fbe3a2b":{
      "scriptId":"u2"},
    "90b5c806195f410ebb67b312dc9d5570":{
      "scriptId":"u3"},
    "07c0091e4ccb484c9822c008d9ee57cc":{
      "scriptId":"u4"},
    "a479f2fd95cb4c998777ebb768529cb0":{
      "scriptId":"u5"},
    "164cef784acc4fdbbc1eba6a71bce106":{
      "scriptId":"u6"},
    "ea6d0f2057b24302b69b7464a53916b2":{
      "scriptId":"u7"},
    "7c80ae15702742c2b7be2bec97c2bd0f":{
      "scriptId":"u8"},
    "f4e525e098334d29b6077c6a5d78e4e3":{
      "scriptId":"u9"},
    "73ea2c78f9c24fb18e680b123e8bd4f1":{
      "scriptId":"u10"},
    "8797708929a547bc9c5e5fa3ee419061":{
      "scriptId":"u11"},
    "34f081cd2eee4c388f7f26754b09bd97":{
      "scriptId":"u12"},
    "cc31ee88883347d081a1dc2827252b3d":{
      "scriptId":"u13"},
    "7474c135860a4cde8e2589d0dbcd4dc9":{
      "scriptId":"u14"},
    "8243501d209e44838c78a59d70d810ec":{
      "scriptId":"u15"},
    "7329b65009504c3b86d018e2491e1946":{
      "scriptId":"u16"},
    "84faee81e6d04764a8992dd8a9aeece4":{
      "scriptId":"u17"},
    "e0994a3dfd9045a3ae36db88315effee":{
      "scriptId":"u18"},
    "e5ba7e96a159489d9db24322cfaf55f7":{
      "scriptId":"u19"},
    "1bf4812d62b2459b96a1bf549719c74d":{
      "scriptId":"u20"},
    "58823c4cd1a648119c86b7a3517d2703":{
      "scriptId":"u21"},
    "beec299f260d411db542c1dad98eb379":{
      "scriptId":"u22"},
    "13e0c8b50f844816892a8985998ad8c1":{
      "scriptId":"u23"},
    "67ea05fe666a4a02bd02d05901b3b1ba":{
      "scriptId":"u24"},
    "9b33cbe8fdd945ec9aeb6657e0fa1705":{
      "scriptId":"u25"},
    "52705254cfa441e293d68f71d22794aa":{
      "scriptId":"u26"},
    "35593a4a1a5d4d869d220b7ddf6ebead":{
      "scriptId":"u27"},
    "797baf236d5c44fea1b6b9f318ccc2d0":{
      "scriptId":"u28"},
    "0bd2dde083a041059cf9a90db90a7da7":{
      "scriptId":"u29"},
    "af51e7313ba04849930913da1f801413":{
      "scriptId":"u30"},
    "20baac38e6a549eca5b1a6f05b3d588b":{
      "scriptId":"u31"},
    "b165fca23cdd46579a2d11d310dd77e4":{
      "scriptId":"u32"},
    "9075605d39114ac79bba346a283ce309":{
      "scriptId":"u33"},
    "da47d477e43544199d33e304b34e078a":{
      "scriptId":"u34"},
    "6e1d359d0023470f8c0d2ff6e8c9a204":{
      "scriptId":"u35"},
    "7941537f56634803a4551ed9a57006ba":{
      "scriptId":"u36"},
    "c59b44a4ba5e4f0c98695b5c2eb9b6a7":{
      "scriptId":"u37"},
    "884ff0099c414207b48eafd2236a23d8":{
      "scriptId":"u38"},
    "da2e97b87bcd4290aa328c993af6d74a":{
      "scriptId":"u39"},
    "61828db2b6d04244a27029a7a6682193":{
      "scriptId":"u40"},
    "0e67ef0a306441c2b057b8481c4f1dd6":{
      "scriptId":"u41"},
    "60ad1ead65ba4edb8e908748e123c3cd":{
      "scriptId":"u42"},
    "226f7dcdd6bd49058a84e1bd54923499":{
      "scriptId":"u43"},
    "7265254eb45a4c3981e6633cc69c61d4":{
      "scriptId":"u44"},
    "457c04c48f14438b94bbb0d067392103":{
      "scriptId":"u45"},
    "1ec49573e43741f19002c4d99e36f41e":{
      "scriptId":"u46"},
    "241b920c330443d689ad7e313fe66b58":{
      "scriptId":"u47"},
    "d8530796a494488aa4fe6383f8eead18":{
      "scriptId":"u48"},
    "54dc2b7d3a124b1c95f5415d5f97174f":{
      "scriptId":"u49"},
    "0b5f5c8bc180495da29c626fb40c733e":{
      "scriptId":"u50"},
    "bbce6d3053f444deab95e1736dfe20cf":{
      "scriptId":"u51"},
    "ca80a6a05e5f42edb1715fcc0c6f75dd":{
      "scriptId":"u52"},
    "85c14300a9e846b4a6bc6ad2b3c32121":{
      "scriptId":"u53"},
    "a1ca9a2f319e403fa26e64bd610e86ac":{
      "scriptId":"u54"},
    "e424c042fb7a42c28fd39a0ce5e63293":{
      "scriptId":"u55"},
    "6afb87ceebc94d70957465c2629e7793":{
      "scriptId":"u56"},
    "4a4a4b37db4a423d9f0a6cdc9b626ce1":{
      "scriptId":"u57"},
    "587204185c86400ebb731d2f3780861e":{
      "scriptId":"u58"},
    "bd1eac3a086843babcfcd2a3c4fa3e1a":{
      "scriptId":"u59"},
    "86b42cd9aecc43a391481f4a195a2eb1":{
      "scriptId":"u60"},
    "8b18deed67284f5da308607567b7b8b6":{
      "scriptId":"u61"},
    "44b6d90958a047a1b9eaa5f32499c8b7":{
      "scriptId":"u62"},
    "fde4c6beaf47483a9a764a8d5ddadc57":{
      "scriptId":"u63"},
    "0325f91a1c174e80bc6d8aa3f745eabd":{
      "scriptId":"u64"},
    "6d9dfb4d8d6f4f65a53e1be44bf205ff":{
      "scriptId":"u65"},
    "7df885a38a5e4acab960fd1507acfa75":{
      "scriptId":"u66"},
    "c1a22ec3f5084e7c81ae4fec73d58f67":{
      "scriptId":"u67"},
    "8448326ce64e4659b2f4313d86fc5303":{
      "scriptId":"u68"},
    "46de0d459421411d8e21f1a40e7ac4d5":{
      "scriptId":"u69"},
    "c6c99283b2c74c41b70dc296c39846ce":{
      "scriptId":"u70"},
    "4454a9c87c594894988156a16b3fbc72":{
      "scriptId":"u71"},
    "d080e472e0864ecf93cf545027767e0d":{
      "scriptId":"u72"},
    "0be469f0d35546bcb2d540be2aa4485b":{
      "scriptId":"u73"},
    "d8946fff331546b4b6ca783605d5606d":{
      "scriptId":"u74"},
    "df83295f4f6c4407aa9482e959df4329":{
      "scriptId":"u75"},
    "91daef16bc2145c08cbc0c092aeb83c0":{
      "scriptId":"u76"},
    "3071c57621d94dc7bbcb2d63dbcb1654":{
      "scriptId":"u77"},
    "6c1b8a4c18e0436eb4a8a819986e0669":{
      "scriptId":"u78"},
    "1cbb4e7bc8e14fadba5e247fd0030cdd":{
      "scriptId":"u79"},
    "631bd708eb4a4e22be5a8809c302c5f2":{
      "scriptId":"u80"},
    "89446c0166d142919dbd765f18b869df":{
      "scriptId":"u81"},
    "20d2f977ea6d495abb176935636fb65a":{
      "scriptId":"u82"},
    "37c21a335faf419bb393d4d4ca515e76":{
      "scriptId":"u83"},
    "a1d81105c2d64ddcba24170aa1dae468":{
      "scriptId":"u84"},
    "7da6345fe0714cbd80776c688f97fb52":{
      "scriptId":"u85"},
    "7a3651b568cc4d8fb24245e4e8af78bb":{
      "scriptId":"u86"},
    "67ec8d53320148a68177db951353c182":{
      "scriptId":"u87"},
    "316a3477fa2d43588cdcb108732a2022":{
      "scriptId":"u88"},
    "0b0cd1c7a3d64df59eb67211d5c4c608":{
      "scriptId":"u89"},
    "aab61226eab14b9aa472573b0386bccb":{
      "scriptId":"u90"},
    "41f547738bbd409db1a1c18159cbba5d":{
      "scriptId":"u91"},
    "aba0633817534c919102371c253a3060":{
      "scriptId":"u92"},
    "fcda05bb9fa74d79969a5489f10d55a9":{
      "scriptId":"u93"},
    "82781906588d498193082d18d664875a":{
      "scriptId":"u94"},
    "f48814dc3b9b46d9b6dcb3c2c9259a1d":{
      "scriptId":"u95"},
    "464ae458ccc142678d8bd531a4f1fcb3":{
      "scriptId":"u96"},
    "660d6cde7bf24edf98acae3325cc7b8e":{
      "scriptId":"u97"},
    "3f61739b059b47e59a30610aad16d193":{
      "scriptId":"u98"},
    "e815bac68d6d4fdea5fe1b2697872c3c":{
      "scriptId":"u99"}}});