$axure.loadCurrentPage({
  "url":"查看举报.html",
  "generationDate":new Date(1447684049074.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b0bef2aa1b624a909bd0a41e189a0ee4",
    "type":"Axure:Page",
    "name":"查看举报",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e54b70f8ac0444d9b92ad8a6831b94b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":382},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978cf48610584b1e8fb502342b9deb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":382},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看举报/u0.png"}},
{
          "id":"0418a572a70641d1b10d9e5c9fbe3a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b5c806195f410ebb67b312dc9d5570",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"07c0091e4ccb484c9822c008d9ee57cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a479f2fd95cb4c998777ebb768529cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"164cef784acc4fdbbc1eba6a71bce106",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":77},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea6d0f2057b24302b69b7464a53916b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":77},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"7c80ae15702742c2b7be2bec97c2bd0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":136},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4e525e098334d29b6077c6a5d78e4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":136},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73ea2c78f9c24fb18e680b123e8bd4f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":136},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8797708929a547bc9c5e5fa3ee419061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":136},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"可点击进入该机构详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc3c2a0a1431436a8a6085d2906f1456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":171},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b606692d34e43f088590798041ebf15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":171},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7d591ab635c44079bf2f70d0d53c83e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":171},
            "size":{
              "width":439,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fea835650841b9ad5859bd09d214ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":171},
                "size":{
                  "width":439,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72eb51df262441eba80609816aee3465",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":237},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719d055a73774912be9ade4af5a57be7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":237},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af95e8a5f817472eab7ffccd78e727b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":237},
            "size":{
              "width":329,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb67893110d493ba006f82c323cabba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":237},
                "size":{
                  "width":329,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34f081cd2eee4c388f7f26754b09bd97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":274},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc31ee88883347d081a1dc2827252b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":274},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7474c135860a4cde8e2589d0dbcd4dc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":271,
              "y":274},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8243501d209e44838c78a59d70d810ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":271,
                  "y":274},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"发起举报的用户名，可点击进入该用户详情"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7329b65009504c3b86d018e2491e1946",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":349},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84faee81e6d04764a8992dd8a9aeece4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":349},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0994a3dfd9045a3ae36db88315effee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":336,
              "y":389},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ba7e96a159489d9db24322cfaf55f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":336,
                  "y":389},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"1bf4812d62b2459b96a1bf549719c74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":408,
              "y":389},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58823c4cd1a648119c86b7a3517d2703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":408,
                  "y":389},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"beec299f260d411db542c1dad98eb379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":271,
              "y":349},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e0c8b50f844816892a8985998ad8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":271,
                  "y":349},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89282ff760984707a4cb7f981d095370",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":840},
            "size":{
              "width":650,
              "height":182},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aacf3a4e936d40318d5cc65120368f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":840},
                "size":{
                  "width":650,
                  "height":182},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看举报/u32.png"}},
{
          "id":"c72faacaa3d34a06b4bfa651ea2f5fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":840},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da957d1727d490884a6235aeb893550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":840},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"9f56dace23de4cf7bbc8145cefff667f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":848},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15db921f86704ee8bf6c2a5efcf81d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":848},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9caaa05cc6c1468c9d093d4044510391",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":849},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3042e912660741239ef927ed717fd48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":849},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"093d978325ff468d9541c75dcd7f7a05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":360,
              "y":981},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3ce79b9792435385d33988de82695c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":360,
                  "y":981},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"9fe6917feab141bf9e911685a571b367",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":921},
            "size":{
              "width":445,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61df1dbc4134eff95ebbb2589186591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":921},
                "size":{
                  "width":445,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"若涉及到包含回复的评论，则同时删除相关回复评论"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5add9f16d9e475aa55e401e30d55dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":432,
              "y":989},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44748700b54e4792a7cf5681c28838a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":432,
                  "y":989},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67ea05fe666a4a02bd02d05901b3b1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "location":{
              "x":490,
              "y":397},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b33cbe8fdd945ec9aeb6657e0fa1705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "location":{
                  "x":490,
                  "y":397},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb50f3afb4094103a22135811d9be835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":190,
              "y":308},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a047c5c97a43a28d67dee234edb394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":190,
                  "y":308},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abc289e57bc5448c9a815a8ee1e44d4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "lineSpacing":"20px",
            "location":{
              "x":271,
              "y":304},
            "size":{
              "width":113,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875484b9486e4ce7b71fb52e7a9621f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "lineSpacing":"20px",
                "location":{
                  "x":271,
                  "y":304},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1e54b70f8ac0444d9b92ad8a6831b94b":{
      "scriptId":"u0"},
    "978cf48610584b1e8fb502342b9deb96":{
      "scriptId":"u1"},
    "0418a572a70641d1b10d9e5c9fbe3a2b":{
      "scriptId":"u2"},
    "90b5c806195f410ebb67b312dc9d5570":{
      "scriptId":"u3"},
    "07c0091e4ccb484c9822c008d9ee57cc":{
      "scriptId":"u4"},
    "a479f2fd95cb4c998777ebb768529cb0":{
      "scriptId":"u5"},
    "164cef784acc4fdbbc1eba6a71bce106":{
      "scriptId":"u6"},
    "ea6d0f2057b24302b69b7464a53916b2":{
      "scriptId":"u7"},
    "7c80ae15702742c2b7be2bec97c2bd0f":{
      "scriptId":"u8"},
    "f4e525e098334d29b6077c6a5d78e4e3":{
      "scriptId":"u9"},
    "73ea2c78f9c24fb18e680b123e8bd4f1":{
      "scriptId":"u10"},
    "8797708929a547bc9c5e5fa3ee419061":{
      "scriptId":"u11"},
    "bc3c2a0a1431436a8a6085d2906f1456":{
      "scriptId":"u12"},
    "4b606692d34e43f088590798041ebf15":{
      "scriptId":"u13"},
    "a7d591ab635c44079bf2f70d0d53c83e":{
      "scriptId":"u14"},
    "95fea835650841b9ad5859bd09d214ab":{
      "scriptId":"u15"},
    "72eb51df262441eba80609816aee3465":{
      "scriptId":"u16"},
    "719d055a73774912be9ade4af5a57be7":{
      "scriptId":"u17"},
    "af95e8a5f817472eab7ffccd78e727b7":{
      "scriptId":"u18"},
    "bcb67893110d493ba006f82c323cabba":{
      "scriptId":"u19"},
    "34f081cd2eee4c388f7f26754b09bd97":{
      "scriptId":"u20"},
    "cc31ee88883347d081a1dc2827252b3d":{
      "scriptId":"u21"},
    "7474c135860a4cde8e2589d0dbcd4dc9":{
      "scriptId":"u22"},
    "8243501d209e44838c78a59d70d810ec":{
      "scriptId":"u23"},
    "7329b65009504c3b86d018e2491e1946":{
      "scriptId":"u24"},
    "84faee81e6d04764a8992dd8a9aeece4":{
      "scriptId":"u25"},
    "e0994a3dfd9045a3ae36db88315effee":{
      "scriptId":"u26"},
    "e5ba7e96a159489d9db24322cfaf55f7":{
      "scriptId":"u27"},
    "1bf4812d62b2459b96a1bf549719c74d":{
      "scriptId":"u28"},
    "58823c4cd1a648119c86b7a3517d2703":{
      "scriptId":"u29"},
    "beec299f260d411db542c1dad98eb379":{
      "scriptId":"u30"},
    "13e0c8b50f844816892a8985998ad8c1":{
      "scriptId":"u31"},
    "89282ff760984707a4cb7f981d095370":{
      "scriptId":"u32"},
    "aacf3a4e936d40318d5cc65120368f56":{
      "scriptId":"u33"},
    "c72faacaa3d34a06b4bfa651ea2f5fcf":{
      "scriptId":"u34"},
    "7da957d1727d490884a6235aeb893550":{
      "scriptId":"u35"},
    "9f56dace23de4cf7bbc8145cefff667f":{
      "scriptId":"u36"},
    "15db921f86704ee8bf6c2a5efcf81d80":{
      "scriptId":"u37"},
    "9caaa05cc6c1468c9d093d4044510391":{
      "scriptId":"u38"},
    "3042e912660741239ef927ed717fd48f":{
      "scriptId":"u39"},
    "093d978325ff468d9541c75dcd7f7a05":{
      "scriptId":"u40"},
    "5a3ce79b9792435385d33988de82695c":{
      "scriptId":"u41"},
    "9fe6917feab141bf9e911685a571b367":{
      "scriptId":"u42"},
    "b61df1dbc4134eff95ebbb2589186591":{
      "scriptId":"u43"},
    "e5add9f16d9e475aa55e401e30d55dfb":{
      "scriptId":"u44"},
    "44748700b54e4792a7cf5681c28838a8":{
      "scriptId":"u45"},
    "67ea05fe666a4a02bd02d05901b3b1ba":{
      "scriptId":"u46"},
    "9b33cbe8fdd945ec9aeb6657e0fa1705":{
      "scriptId":"u47"},
    "fb50f3afb4094103a22135811d9be835":{
      "scriptId":"u48"},
    "b7a047c5c97a43a28d67dee234edb394":{
      "scriptId":"u49"},
    "abc289e57bc5448c9a815a8ee1e44d4a":{
      "scriptId":"u50"},
    "875484b9486e4ce7b71fb52e7a9621f4":{
      "scriptId":"u51"}}});