$axure.loadCurrentPage({
  "url":"新增广告.html",
  "generationDate":new Date(1447684050935.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d84a72eaee984f7c859eb693fdaf647d",
    "type":"Axure:Page",
    "name":"新增广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a996e8715a9e4bc5a37cb6e7adce299c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":332},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9d8bb052f9a4bcbb6252fb9f35f3d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":332},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增广告/u0.png"}},
{
          "id":"5b63628489e148b5898a4a426314b318",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":650,
              "height":33},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53660443bbc942f5be40bd22cf3bcc2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":650,
                  "height":33},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增机构/u2.png"}},
{
          "id":"0f70a94d9d974624982ac745891ff1e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":117,
              "y":76},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3225d9981dd41a1a6db2a8bd6cfb818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":117,
                  "y":76},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e7c24d9e3094bf0b2da5c7ac32cb40f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "opacity":"1"}},
            "opacity":"0.4",
            "location":{
              "x":726,
              "y":77},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0049ba5e46c44d7b9efeca6bfe71748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "opacity":"1"}},
                "opacity":"0.4",
                "location":{
                  "x":726,
                  "y":77},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构详情/u996.png",
            "mouseOver~":"images/机构详情/u996.png"}},
{
          "id":"547683158290454a91fe84f21ca08f90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":198,
              "y":131},
            "size":{
              "width":69,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e279c7d83a4f448454382e4f00b1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":198,
                  "y":131},
                "size":{
                  "width":69,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd9efd083c264d84bf374c1775667d16",
          "label":"推荐位",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":166},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0c258ffcb907427cb896fefb71dacec0",
              "label":"首页焦点图",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1423cc8bc53043a6a0efc903cb16abb1",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":69,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c605a3c01709489a9968ef1e3523971b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":0,
                          "y":35},
                        "size":{
                          "width":69,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b64a22de660d4319a12737953102a783",
                  "label":"产品标题",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请输入该图片名称"},
{
                  "id":"0a295881ca874add8d35704fc78049a7",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":81,
                      "y":0},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88e9197214e7473abf0584092a6fb885",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":81,
                          "y":0},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"62101179be6745b2891e7dd66983775b",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":5,
                      "y":74},
                    "size":{
                      "width":64,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"312cd3458f8e42e490cbfd3882d8883e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":5,
                          "y":74},
                        "size":{
                          "width":64,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f42a09866cc74289a054353e2dec1a97",
                  "label":"产品标题",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":69},
                    "size":{
                      "width":190,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请输入该图片准备链接的地址"},
{
                  "id":"0e63ffe443e04d669e2cebac5bb331b7",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":292,
                      "y":74},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23fe35fc1ede455e9312fc12cb16f222",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":292,
                          "y":74},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "描述":"点击选择机构展开机构列表，选中一个机构后，左侧图片链接变为该机构的名称；在首页点开该图片时将进入该机构详情/相关链接"},
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"312d90a0374f42fea52268d7e9cfb5b5",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":-1,
                      "y":114},
                    "size":{
                      "width":72,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"216fb9538cab4c09aa8994c955cc0cd7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":-1,
                          "y":114},
                        "size":{
                          "width":72,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7b9d796bec3e468b918eee21c24f7191",
                  "label":"产品标题",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":109},
                    "size":{
                      "width":190,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "annotation":{
                    "描述":"请结合地图接口定义该字段，尽量避免输入经纬度"},
                  "placeholderText":"请输入该广告位权重"},
{
                  "id":"1bb1e742bcd649678cb78ba24a006aaf",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":144},
                    "size":{
                      "width":323,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64533c4c7e604814b4e4fc7c01695d44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":81,
                          "y":144},
                        "size":{
                          "width":323,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d1e14c3722d94fa8a71c09e75590bb44",
              "label":"推荐位",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"91e39a0fe04346cc934ec6643e497dec",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":5,
                      "y":18},
                    "size":{
                      "width":64,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d7127bb0660418ea392548f10cfb2d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":5,
                          "y":18},
                        "size":{
                          "width":64,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9ac799e921014cef8d11e8be97a31e6e",
                  "label":"产品标题",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":13},
                    "size":{
                      "width":190,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请选择机构"},
{
                  "id":"7d9bdadcf7074489ae7b1c4740bb7578",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "opacity":"0.7"}},
                    "location":{
                      "x":292,
                      "y":18},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa96921aac0a4fd489b0651d70208fa1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "opacity":"0.7"}},
                        "location":{
                          "x":292,
                          "y":18},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "annotation":{
                    "描述":"点击选择机构展开机构列表，选中一个机构后，左侧图片链接变为该机构的名称；在首页点开该图片时将进入该机构详情/相关链接"},
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"29e9e295394349b8add7a9aca222f427",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":-1,
                      "y":58},
                    "size":{
                      "width":72,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec479647e6264850a09b0b560b62a489",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":-1,
                          "y":58},
                        "size":{
                          "width":72,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f117976f89574729a4b4f6112d8a7d78",
                  "label":"产品标题",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":53},
                    "size":{
                      "width":190,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "annotation":{
                    "描述":"请结合地图接口定义该字段，尽量避免输入经纬度"},
                  "placeholderText":"请输入该广告位权重"},
{
                  "id":"0a6b61244dd044f5bd1f65644ef9c935",
                  "label":"",
                  "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":81,
                      "y":88},
                    "size":{
                      "width":323,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c4bf2cfbf454efca706b1afd29a8775",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd9efd083c264d84bf374c1775667d16",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":81,
                          "y":88},
                        "size":{
                          "width":323,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"fc9221cfeebb43819abe0e453c7f30e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":372,
              "y":349},
            "size":{
              "width":62,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aaec39ba26846b28024dfea1162d365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":372,
                  "y":349},
                "size":{
                  "width":62,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息管理/u101.png",
            "mouseOver~":"images/信息管理/u101_mouseOver.png"}},
{
          "id":"0973d35bb1ed4e68b920b8995efb4b50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "location":{
              "x":444,
              "y":357},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1de51d9818d47e7be39c5937b2d4a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "location":{
                  "x":444,
                  "y":357},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"13f21df6a60a49a481480fba8131238b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":126},
            "size":{
              "width":153,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 当前部件 = &quot;首页焦点图&quot; 或 选中项值 当前部件 = &quot;首页图片广告位&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetSelectedOption",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":true,
                            "isFocused":false,
                            "isTarget":false}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"首页焦点图",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetSelectedOption",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":true,
                            "isFocused":false,
                            "isTarget":false}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"首页图片广告位",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 推荐位 到 首页焦点图",
                      "panelsToStates":[{
                          "panelPath":["dd9efd083c264d84bf374c1775667d16"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 推荐位 到 推荐位",
                      "panelsToStates":[{
                          "panelPath":["dd9efd083c264d84bf374c1775667d16"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "a996e8715a9e4bc5a37cb6e7adce299c":{
      "scriptId":"u0"},
    "d9d8bb052f9a4bcbb6252fb9f35f3d3b":{
      "scriptId":"u1"},
    "5b63628489e148b5898a4a426314b318":{
      "scriptId":"u2"},
    "53660443bbc942f5be40bd22cf3bcc2d":{
      "scriptId":"u3"},
    "0f70a94d9d974624982ac745891ff1e5":{
      "scriptId":"u4"},
    "c3225d9981dd41a1a6db2a8bd6cfb818":{
      "scriptId":"u5"},
    "4e7c24d9e3094bf0b2da5c7ac32cb40f":{
      "scriptId":"u6"},
    "e0049ba5e46c44d7b9efeca6bfe71748":{
      "scriptId":"u7"},
    "547683158290454a91fe84f21ca08f90":{
      "scriptId":"u8"},
    "93e279c7d83a4f448454382e4f00b1dc":{
      "scriptId":"u9"},
    "dd9efd083c264d84bf374c1775667d16":{
      "scriptId":"u10"},
    "1423cc8bc53043a6a0efc903cb16abb1":{
      "scriptId":"u11"},
    "c605a3c01709489a9968ef1e3523971b":{
      "scriptId":"u12"},
    "b64a22de660d4319a12737953102a783":{
      "scriptId":"u13"},
    "0a295881ca874add8d35704fc78049a7":{
      "scriptId":"u14"},
    "88e9197214e7473abf0584092a6fb885":{
      "scriptId":"u15"},
    "62101179be6745b2891e7dd66983775b":{
      "scriptId":"u16"},
    "312cd3458f8e42e490cbfd3882d8883e":{
      "scriptId":"u17"},
    "f42a09866cc74289a054353e2dec1a97":{
      "scriptId":"u18"},
    "0e63ffe443e04d669e2cebac5bb331b7":{
      "scriptId":"u19"},
    "23fe35fc1ede455e9312fc12cb16f222":{
      "scriptId":"u20"},
    "312d90a0374f42fea52268d7e9cfb5b5":{
      "scriptId":"u21"},
    "216fb9538cab4c09aa8994c955cc0cd7":{
      "scriptId":"u22"},
    "7b9d796bec3e468b918eee21c24f7191":{
      "scriptId":"u23"},
    "1bb1e742bcd649678cb78ba24a006aaf":{
      "scriptId":"u24"},
    "64533c4c7e604814b4e4fc7c01695d44":{
      "scriptId":"u25"},
    "91e39a0fe04346cc934ec6643e497dec":{
      "scriptId":"u26"},
    "7d7127bb0660418ea392548f10cfb2d8":{
      "scriptId":"u27"},
    "9ac799e921014cef8d11e8be97a31e6e":{
      "scriptId":"u28"},
    "7d9bdadcf7074489ae7b1c4740bb7578":{
      "scriptId":"u29"},
    "fa96921aac0a4fd489b0651d70208fa1":{
      "scriptId":"u30"},
    "29e9e295394349b8add7a9aca222f427":{
      "scriptId":"u31"},
    "ec479647e6264850a09b0b560b62a489":{
      "scriptId":"u32"},
    "f117976f89574729a4b4f6112d8a7d78":{
      "scriptId":"u33"},
    "0a6b61244dd044f5bd1f65644ef9c935":{
      "scriptId":"u34"},
    "6c4bf2cfbf454efca706b1afd29a8775":{
      "scriptId":"u35"},
    "fc9221cfeebb43819abe0e453c7f30e6":{
      "scriptId":"u36"},
    "5aaec39ba26846b28024dfea1162d365":{
      "scriptId":"u37"},
    "0973d35bb1ed4e68b920b8995efb4b50":{
      "scriptId":"u38"},
    "b1de51d9818d47e7be39c5937b2d4a76":{
      "scriptId":"u39"},
    "13f21df6a60a49a481480fba8131238b":{
      "scriptId":"u40"}}});